services:
  api:
    container_name: traceway_api_${ENV}
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    depends_on:
      - db
    image: traceway_api_${ENV}
    networks:
      - traceway_net
    restart: always
    env_file:
      - .env.${ENV}

  db:
    container_name: ${DB_HOST}
    image: postgres:14.3
    restart: always
    ports:
      - '${DB_EXPOSED_PORT}:${DB_PORT}'
    networks:
      - traceway_net
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data

networks:
  traceway_net:
